name: Update News Feed Daily

on:
  schedule:
    - cron: "0 20 * * *"  # Scheduler: Daily at 6 AM (UTC+10)
  workflow_dispatch:       # Manual trigger
  push:                    
    branches:
      - main
    paths:
      - 'feeds/*.json'       # Only trigger if json files directly inside /feeds/ is changed, not subfolders or other files

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install feedparser

      - name: Run personalised news feed python script
        working-directory: ./src
        run: python main.py

      - name: Copy public files
        run: |
          mkdir -p ./public
          cp index.html ./public/
          cp config.html ./public/

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  deploy:
    needs: update
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
